### ISSUE TITLE
2021-12-14 Peer-to-peer code review

### ISSUE THREAD

**Issue by vechicin** [Lucas-Masaba/to_do_list#8]
# Fantastic job guys! 👍 💯 😄 🥇 

My only recommendation would be to update the "test" key in the package.json file to include testing coverage. It should look like this: "test: jest --coverage". If you do decide to implement this change, make sure you run the tests again and have them all get to 100%!

## Once again, fantastic job, your code is very readable, and the way you handled your mocks was very organized! ✅ 🤓

**Comment by Mre55** [comment]
- https://github.com/Lucas-Masaba/to_do_list/blob/3de686d2176f2e604ef03895a781080470be63e2/src/handlers.test.js#L71 the textContent can be accessed with description property since we already have that property on the array.

**Comment by ShadyShawkat** [comment]
# Hey @vechicin, 👋🏻 

Thank you for the observations and suggestions. We actually planned on using the "coverage" flag, but we had a lot of issues with the linters. So, we decided not to use it.

**Comment by ShadyShawkat** [comment]
#Hey @Mre55, 👋🏻 

Thank you for taking the time and looking through my code. 
https://github.com/Lucas-Masaba/to_do_list/blob/3de686d2176f2e604ef03895a781080470be63e2/src/handlers.test.js#L69-L72
This test is testing the DOM, not the actual object. We are getting the descriptions in the DOM and seeing if the second one has the new text.
